$kind: http-example
request:
  url: "{{baseUrl}}/api/volunteers/tasks"
  method: POST
  headers:
    - key: Content-Type
      value: application/json
    - key: Accept
      value: application/json
    - key: Authorization
      value: Bearer <token>
      description: "Added as a part of security scheme: bearer"
  body:
    type: json
    content: |-
      {
        "request_id": "dc765fc0-cf0f-efb6-840a-507c5da6cd3f",
        "volunteer_user_id": "9df3e9a2-d641-86a5-ced5-b154b7cb6856",
        "title": "string",
        "instructions": null
      }
response:
  statusCode: 201
  statusText: Created
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "id": "bdcde238-510b-aaac-ee37-5a7f6c17be66",
        "request_id": "b3613ae3-307e-69ce-52c9-da3812441b40",
        "volunteer_user_id": "95ec7814-d207-6118-8a1a-08d496ab3f54",
        "title": "string",
        "instructions": "string",
        "status": "in_progress",
        "created_at": "1982-06-17T15:33:04.455Z",
        "accepted_at": "2022-04-06T14:13:20.059Z",
        "completed_at": null
      }
order: 1000
