"""init_iam

Revision ID: 91e8fdce8367
Revises: 
Create Date: 2026-07-07 21:19:11.732497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '91e8fdce8367'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('routing_key', sa.String(length=120), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id'),
    schema='schema_iam'
    )
    op.create_index(op.f('ix_schema_iam_outbox_created_at'), 'outbox', ['created_at'], unique=False, schema='schema_iam')
    op.create_table('signing_keys',
    sa.Column('kid', sa.String(length=32), nullable=False),
    sa.Column('public_pem', sa.Text(), nullable=False),
    sa.Column('private_ref', sa.String(length=300), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='schema_iam'
    )
    op.create_index(op.f('ix_schema_iam_signing_keys_kid'), 'signing_keys', ['kid'], unique=True, schema='schema_iam')
    op.create_table('tenants',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='schema_iam'
    )
    op.create_index(op.f('ix_schema_iam_tenants_slug'), 'tenants', ['slug'], unique=True, schema='schema_iam')
    op.create_table('users',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['schema_iam.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'email', name='uq_users_tenant_email'),
    schema='schema_iam'
    )
    op.create_index(op.f('ix_schema_iam_users_email'), 'users', ['email'], unique=False, schema='schema_iam')
    op.create_index(op.f('ix_schema_iam_users_tenant_id'), 'users', ['tenant_id'], unique=False, schema='schema_iam')
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rotated_from', sa.UUID(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['schema_iam.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash'),
    schema='schema_iam'
    )
    op.create_index(op.f('ix_schema_iam_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False, schema='schema_iam')
    op.create_table('role_assignments',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['schema_iam.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role', name='uq_role_assignments_user_role'),
    schema='schema_iam'
    )
    op.create_index(op.f('ix_schema_iam_role_assignments_tenant_id'), 'role_assignments', ['tenant_id'], unique=False, schema='schema_iam')
    op.create_index(op.f('ix_schema_iam_role_assignments_user_id'), 'role_assignments', ['user_id'], unique=False, schema='schema_iam')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schema_iam_role_assignments_user_id'), table_name='role_assignments', schema='schema_iam')
    op.drop_index(op.f('ix_schema_iam_role_assignments_tenant_id'), table_name='role_assignments', schema='schema_iam')
    op.drop_table('role_assignments', schema='schema_iam')
    op.drop_index(op.f('ix_schema_iam_refresh_tokens_user_id'), table_name='refresh_tokens', schema='schema_iam')
    op.drop_table('refresh_tokens', schema='schema_iam')
    op.drop_index(op.f('ix_schema_iam_users_tenant_id'), table_name='users', schema='schema_iam')
    op.drop_index(op.f('ix_schema_iam_users_email'), table_name='users', schema='schema_iam')
    op.drop_table('users', schema='schema_iam')
    op.drop_index(op.f('ix_schema_iam_tenants_slug'), table_name='tenants', schema='schema_iam')
    op.drop_table('tenants', schema='schema_iam')
    op.drop_index(op.f('ix_schema_iam_signing_keys_kid'), table_name='signing_keys', schema='schema_iam')
    op.drop_table('signing_keys', schema='schema_iam')
    op.drop_index(op.f('ix_schema_iam_outbox_created_at'), table_name='outbox', schema='schema_iam')
    op.drop_table('outbox', schema='schema_iam')
    # ### end Alembic commands ###
