"""add latitude longitude to disaster_events

Revision ID: 2a347900fcbc
Revises: 2890f7e11c81
Create Date: 2026-07-31 13:55:57.977741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2a347900fcbc'
down_revision: Union[str, None] = '2890f7e11c81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('disaster_events', sa.Column('latitude', sa.Float(), nullable=True), schema='schema_volunteer')
    op.add_column('disaster_events', sa.Column('longitude', sa.Float(), nullable=True), schema='schema_volunteer')
    # ### end Alembic commands ###


def downgrade() -> None:
   # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('disaster_events', 'longitude', schema='schema_volunteer')
    op.drop_column('disaster_events', 'latitude', schema='schema_volunteer')
    # ### end Alembic commands ###