"""Add victim_request table

Revision ID: 66875bc6d126
Revises: 2a347900fcbc
Create Date: 2026-08-01 18:41:35.157918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '66875bc6d126'
down_revision: Union[str, None] = '2a347900fcbc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('volunteer_reports', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=True,
               schema='schema_volunteer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('volunteer_reports', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'PENDING'::character varying"),
               existing_nullable=True,
               schema='schema_volunteer')
    # ### end Alembic commands ###
