"""init_volunteer

Revision ID: a70c2c6f2de0
Revises: 
Create Date: 2026-07-14 01:13:28.499473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a70c2c6f2de0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disaster_events',
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_district', sa.String(length=40), nullable=False),
    sa.Column('broadcast_type', sa.Enum('RADIUS_L1', 'RADIUS_L2', 'TARGETED', name='broadcast_type', schema='schema_volunteer', inherit_schema=True), nullable=False),
    sa.Column('target_districts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('DECLARED', 'BROADCASTING', 'TEAM_FORMED', 'CLOSED', name='event_status', schema='schema_volunteer', inherit_schema=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='schema_volunteer'
    )
    op.create_index(op.f('ix_schema_volunteer_disaster_events_source_district'), 'disaster_events', ['source_district'], unique=False, schema='schema_volunteer')
    op.create_index(op.f('ix_schema_volunteer_disaster_events_status'), 'disaster_events', ['status'], unique=False, schema='schema_volunteer')
    op.create_index(op.f('ix_schema_volunteer_disaster_events_tenant_id'), 'disaster_events', ['tenant_id'], unique=False, schema='schema_volunteer')
    op.create_table('outbox',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('routing_key', sa.String(length=120), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id'),
    schema='schema_volunteer'
    )
    op.create_index(op.f('ix_schema_volunteer_outbox_created_at'), 'outbox', ['created_at'], unique=False, schema='schema_volunteer')
    op.create_table('processed_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('event_id'),
    schema='schema_volunteer'
    )
    op.create_table('volunteer_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('base_district', sa.String(length=40), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('available_status', sa.Boolean(), nullable=False),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='schema_volunteer'
    )
    op.create_index(op.f('ix_schema_volunteer_volunteer_profiles_base_district'), 'volunteer_profiles', ['base_district'], unique=False, schema='schema_volunteer')
    op.create_index('ix_volunteer_profiles_matching', 'volunteer_profiles', ['base_district', 'available_status'], unique=False, schema='schema_volunteer')
    op.create_index('ix_volunteer_profiles_skills', 'volunteer_profiles', ['skills'], unique=False, schema='schema_volunteer', postgresql_using='gin')
    op.create_table('event_requirements',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('skill', sa.String(length=100), nullable=False),
    sa.Column('required_count', sa.Integer(), nullable=False),
    sa.Column('filled_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'FULFILLED', name='requirement_status', schema='schema_volunteer', inherit_schema=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('filled_count >= 0 AND filled_count <= required_count', name='ck_event_requirements_bounds'),
    sa.CheckConstraint('required_count > 0', name='ck_event_requirements_positive'),
    sa.ForeignKeyConstraint(['event_id'], ['schema_volunteer.disaster_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'skill', name='uq_event_requirements_event_skill'),
    schema='schema_volunteer'
    )
    op.create_index(op.f('ix_schema_volunteer_event_requirements_event_id'), 'event_requirements', ['event_id'], unique=False, schema='schema_volunteer')
    op.create_table('event_volunteer_mappings',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('volunteer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('NOTIFIED', 'ACCEPTED', 'DECLINED', 'REJECTED_FULL', 'EN_ROUTE', 'COMPLETED', name='assignment_status', schema='schema_volunteer', inherit_schema=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['schema_volunteer.disaster_events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['schema_volunteer.event_requirements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['volunteer_id'], ['schema_volunteer.volunteer_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'volunteer_id', name='uq_evm_event_volunteer'),
    schema='schema_volunteer'
    )
    op.create_index(op.f('ix_schema_volunteer_event_volunteer_mappings_event_id'), 'event_volunteer_mappings', ['event_id'], unique=False, schema='schema_volunteer')
    op.create_index(op.f('ix_schema_volunteer_event_volunteer_mappings_requirement_id'), 'event_volunteer_mappings', ['requirement_id'], unique=False, schema='schema_volunteer')
    op.create_index(op.f('ix_schema_volunteer_event_volunteer_mappings_status'), 'event_volunteer_mappings', ['status'], unique=False, schema='schema_volunteer')
    op.create_index(op.f('ix_schema_volunteer_event_volunteer_mappings_volunteer_id'), 'event_volunteer_mappings', ['volunteer_id'], unique=False, schema='schema_volunteer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schema_volunteer_event_volunteer_mappings_volunteer_id'), table_name='event_volunteer_mappings', schema='schema_volunteer')
    op.drop_index(op.f('ix_schema_volunteer_event_volunteer_mappings_status'), table_name='event_volunteer_mappings', schema='schema_volunteer')
    op.drop_index(op.f('ix_schema_volunteer_event_volunteer_mappings_requirement_id'), table_name='event_volunteer_mappings', schema='schema_volunteer')
    op.drop_index(op.f('ix_schema_volunteer_event_volunteer_mappings_event_id'), table_name='event_volunteer_mappings', schema='schema_volunteer')
    op.drop_table('event_volunteer_mappings', schema='schema_volunteer')
    op.drop_index(op.f('ix_schema_volunteer_event_requirements_event_id'), table_name='event_requirements', schema='schema_volunteer')
    op.drop_table('event_requirements', schema='schema_volunteer')
    op.drop_index('ix_volunteer_profiles_skills', table_name='volunteer_profiles', schema='schema_volunteer', postgresql_using='gin')
    op.drop_index('ix_volunteer_profiles_matching', table_name='volunteer_profiles', schema='schema_volunteer')
    op.drop_index(op.f('ix_schema_volunteer_volunteer_profiles_base_district'), table_name='volunteer_profiles', schema='schema_volunteer')
    op.drop_table('volunteer_profiles', schema='schema_volunteer')
    op.drop_table('processed_events', schema='schema_volunteer')
    op.drop_index(op.f('ix_schema_volunteer_outbox_created_at'), table_name='outbox', schema='schema_volunteer')
    op.drop_table('outbox', schema='schema_volunteer')
    op.drop_index(op.f('ix_schema_volunteer_disaster_events_tenant_id'), table_name='disaster_events', schema='schema_volunteer')
    op.drop_index(op.f('ix_schema_volunteer_disaster_events_status'), table_name='disaster_events', schema='schema_volunteer')
    op.drop_index(op.f('ix_schema_volunteer_disaster_events_source_district'), table_name='disaster_events', schema='schema_volunteer')
    op.drop_table('disaster_events', schema='schema_volunteer')
    # ### end Alembic commands ###
