$kind: http-example
request:
  url: "{{baseUrl}}/api/volunteers/tasks/:task_id/status?new_status=completed"
  method: PATCH
  headers:
    - key: Accept
      value: application/json
    - key: Authorization
      value: Bearer <token>
      description: "Added as a part of security scheme: bearer"
  queryParams:
    new_status: completed
  pathVariables:
    task_id: 25c6647f-980f-65b6-b02c-77e7160bc6f3
response:
  statusCode: 422
  statusText: Unprocessable Entity (WebDAV) (RFC 4918)
  headers:
    Content-Type: application/json
  body:
    type: json
    content: |-
      {
        "detail": [
          {
            "loc": [
              "string",
              4696
            ],
            "msg": "string",
            "type": "string",
            "input": "",
            "ctx": {}
          },
          {
            "loc": [
              4327,
              "string"
            ],
            "msg": "string",
            "type": "string",
            "input": "",
            "ctx": {}
          }
        ]
      }
order: 2000
