"""init_logistics

Revision ID: ef9ee4c70bd9
Revises: 
Create Date: 2026-07-07 21:18:34.145177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ef9ee4c70bd9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outbox',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('routing_key', sa.String(length=120), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id'),
    schema='schema_logistics'
    )
    op.create_index(op.f('ix_schema_logistics_outbox_created_at'), 'outbox', ['created_at'], unique=False, schema='schema_logistics')
    op.create_table('processed_events',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('event_id'),
    schema='schema_logistics'
    )
    op.create_table('resource_categories',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('form_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='schema_logistics'
    )
    op.create_index(op.f('ix_schema_logistics_resource_categories_tenant_id'), 'resource_categories', ['tenant_id'], unique=False, schema='schema_logistics')
    op.create_table('user_replicas',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('roles', postgresql.ARRAY(sa.String(length=30)), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    schema='schema_logistics'
    )
    op.create_index(op.f('ix_schema_logistics_user_replicas_tenant_id'), 'user_replicas', ['tenant_id'], unique=False, schema='schema_logistics')
    op.create_table('volunteer_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('availability', sa.Enum('AVAILABLE', 'BUSY', 'OFFLINE', name='availability_status', schema='schema_logistics', inherit_schema=True), nullable=False),
    sa.Column('area', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id'),
    schema='schema_logistics'
    )
    op.create_index(op.f('ix_schema_logistics_volunteer_profiles_tenant_id'), 'volunteer_profiles', ['tenant_id'], unique=False, schema='schema_logistics')
    op.create_table('help_requests',
    sa.Column('requester_user_id', sa.UUID(), nullable=True),
    sa.Column('verified_by_user_id', sa.UUID(), nullable=True),
    sa.Column('requester_name', sa.String(length=200), nullable=True),
    sa.Column('requester_phone', sa.String(length=30), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity_needed', sa.Integer(), nullable=False),
    sa.Column('urgency', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='urgency_level', schema='schema_logistics', inherit_schema=True), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'APPROVED', 'IN_PROGRESS', 'FULFILLED', 'REJECTED', 'CANCELLED', name='request_status', schema='schema_logistics', inherit_schema=True), nullable=False),
    sa.Column('extra_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('area', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fulfilled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['schema_logistics.resource_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='schema_logistics'
    )
    op.create_index(op.f('ix_schema_logistics_help_requests_category_id'), 'help_requests', ['category_id'], unique=False, schema='schema_logistics')
    op.create_index(op.f('ix_schema_logistics_help_requests_status'), 'help_requests', ['status'], unique=False, schema='schema_logistics')
    op.create_index(op.f('ix_schema_logistics_help_requests_tenant_id'), 'help_requests', ['tenant_id'], unique=False, schema='schema_logistics')
    op.create_table('inventory_items',
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('quantity_total', sa.Integer(), nullable=False),
    sa.Column('quantity_reserved', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('AVAILABLE', 'RESERVED', 'DEPLETED', 'EXPIRED', name='inventory_status', schema='schema_logistics', inherit_schema=True), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('storage_location', sa.String(length=200), nullable=True),
    sa.Column('donor_name', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['schema_logistics.resource_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='schema_logistics'
    )
    op.create_index(op.f('ix_schema_logistics_inventory_items_category_id'), 'inventory_items', ['category_id'], unique=False, schema='schema_logistics')
    op.create_index(op.f('ix_schema_logistics_inventory_items_tenant_id'), 'inventory_items', ['tenant_id'], unique=False, schema='schema_logistics')
    op.create_table('volunteer_skills',
    sa.Column('volunteer_id', sa.UUID(), nullable=False),
    sa.Column('skill', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['volunteer_id'], ['schema_logistics.volunteer_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='schema_logistics'
    )
    op.create_index(op.f('ix_schema_logistics_volunteer_skills_volunteer_id'), 'volunteer_skills', ['volunteer_id'], unique=False, schema='schema_logistics')
    op.create_table('dispatch_tasks',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('volunteer_user_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by_user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ASSIGNED', 'ACCEPTED', 'IN_PROGRESS', 'COMPLETED', 'DECLINED', 'CANCELLED', name='task_status', schema='schema_logistics', inherit_schema=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['schema_logistics.help_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='schema_logistics'
    )
    op.create_index(op.f('ix_schema_logistics_dispatch_tasks_request_id'), 'dispatch_tasks', ['request_id'], unique=False, schema='schema_logistics')
    op.create_index(op.f('ix_schema_logistics_dispatch_tasks_status'), 'dispatch_tasks', ['status'], unique=False, schema='schema_logistics')
    op.create_index(op.f('ix_schema_logistics_dispatch_tasks_tenant_id'), 'dispatch_tasks', ['tenant_id'], unique=False, schema='schema_logistics')
    op.create_index(op.f('ix_schema_logistics_dispatch_tasks_volunteer_user_id'), 'dispatch_tasks', ['volunteer_user_id'], unique=False, schema='schema_logistics')
    op.create_table('resource_offers',
    sa.Column('donor_user_id', sa.UUID(), nullable=True),
    sa.Column('donor_name', sa.String(length=200), nullable=True),
    sa.Column('donor_phone', sa.String(length=30), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PLEDGED', 'ACCEPTED', 'RECEIVED', 'DECLINED', 'WITHDRAWN', name='offer_status', schema='schema_logistics', inherit_schema=True), nullable=False),
    sa.Column('extra_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('inventory_item_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['schema_logistics.resource_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['schema_logistics.inventory_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='schema_logistics'
    )
    op.create_index(op.f('ix_schema_logistics_resource_offers_category_id'), 'resource_offers', ['category_id'], unique=False, schema='schema_logistics')
    op.create_index(op.f('ix_schema_logistics_resource_offers_status'), 'resource_offers', ['status'], unique=False, schema='schema_logistics')
    op.create_index(op.f('ix_schema_logistics_resource_offers_tenant_id'), 'resource_offers', ['tenant_id'], unique=False, schema='schema_logistics')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schema_logistics_resource_offers_tenant_id'), table_name='resource_offers', schema='schema_logistics')
    op.drop_index(op.f('ix_schema_logistics_resource_offers_status'), table_name='resource_offers', schema='schema_logistics')
    op.drop_index(op.f('ix_schema_logistics_resource_offers_category_id'), table_name='resource_offers', schema='schema_logistics')
    op.drop_table('resource_offers', schema='schema_logistics')
    op.drop_index(op.f('ix_schema_logistics_dispatch_tasks_volunteer_user_id'), table_name='dispatch_tasks', schema='schema_logistics')
    op.drop_index(op.f('ix_schema_logistics_dispatch_tasks_tenant_id'), table_name='dispatch_tasks', schema='schema_logistics')
    op.drop_index(op.f('ix_schema_logistics_dispatch_tasks_status'), table_name='dispatch_tasks', schema='schema_logistics')
    op.drop_index(op.f('ix_schema_logistics_dispatch_tasks_request_id'), table_name='dispatch_tasks', schema='schema_logistics')
    op.drop_table('dispatch_tasks', schema='schema_logistics')
    op.drop_index(op.f('ix_schema_logistics_volunteer_skills_volunteer_id'), table_name='volunteer_skills', schema='schema_logistics')
    op.drop_table('volunteer_skills', schema='schema_logistics')
    op.drop_index(op.f('ix_schema_logistics_inventory_items_tenant_id'), table_name='inventory_items', schema='schema_logistics')
    op.drop_index(op.f('ix_schema_logistics_inventory_items_category_id'), table_name='inventory_items', schema='schema_logistics')
    op.drop_table('inventory_items', schema='schema_logistics')
    op.drop_index(op.f('ix_schema_logistics_help_requests_tenant_id'), table_name='help_requests', schema='schema_logistics')
    op.drop_index(op.f('ix_schema_logistics_help_requests_status'), table_name='help_requests', schema='schema_logistics')
    op.drop_index(op.f('ix_schema_logistics_help_requests_category_id'), table_name='help_requests', schema='schema_logistics')
    op.drop_table('help_requests', schema='schema_logistics')
    op.drop_index(op.f('ix_schema_logistics_volunteer_profiles_tenant_id'), table_name='volunteer_profiles', schema='schema_logistics')
    op.drop_table('volunteer_profiles', schema='schema_logistics')
    op.drop_index(op.f('ix_schema_logistics_user_replicas_tenant_id'), table_name='user_replicas', schema='schema_logistics')
    op.drop_table('user_replicas', schema='schema_logistics')
    op.drop_index(op.f('ix_schema_logistics_resource_categories_tenant_id'), table_name='resource_categories', schema='schema_logistics')
    op.drop_table('resource_categories', schema='schema_logistics')
    op.drop_table('processed_events', schema='schema_logistics')
    op.drop_index(op.f('ix_schema_logistics_outbox_created_at'), table_name='outbox', schema='schema_logistics')
    op.drop_table('outbox', schema='schema_logistics')
    # ### end Alembic commands ###
